"use client";
import './styles/globals.css'
import { Josefin_Sans } from 'next/font/google'
import useUserStore from './stores/userStore'



const josefin = Josefin_Sans({ subsets: ['latin'] })


// export const metadata = {
//   title: 'Mayaluna',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const userName= useUserStore(state => state.name);

  return (
    <html lang="en">
      <body className={josefin.className}>
        {children}
      </body>
    </html>
  )
}
