export const companiasSeguros = [
  { nombre: "ALLIANZ SEGUROS S.A", asistencia: "265" },
  { nombre: "ARL SURA", asistencia: "01800 051 1414" },
  { nombre: "ASEGURADORA SOLIDARIA DE COLOMBIA LTDA", asistencia: "789" },
  { nombre: "AXA COLPATRIA SEGUROS S.A", asistencia: "247" },
  { nombre: "BBVA SEGUROS COLOMBIA S.A", asistencia: "370" },
  {
    nombre: "BERKLEYINTERNACIONAL SEGUROS COLOMBIA S.A",
    asistencia: "6013572727",
  },
  { nombre: "CARDIF COLOMBIA SEGUROS GENERALES S.A", asistencia: "6017455423" },
  { nombre: "CHUBB SEGUROS COLOMBIA S.A", asistencia: "6013190402" },
  { nombre: "COFACE", asistencia: "6016231631" },
  {
    nombre: "COLMENA COMPAÑÍA DE SEGUROS DE VIDA S.A",
    asistencia: "6014010447",
  },
  {
    nombre: "COMPAÑÍA ASEGURADORA DE FIANZAS S.A CONFIANZA",
    asistencia: "6016444690",
  },
  {
    nombre: "COMPAÑÍA DE SEGUROS DE VIDA AURORA S.A",
    asistencia: "6015524570",
  },
  { nombre: "COMPAÑIA MUNDIAL SEGUROS S.A", asistencia: "6013274712" },
  { nombre: "GLOBAL SEGUROS DE VIDA S.A", asistencia: "6017440084" },
  {
    nombre: "GRUPO COLMENA CAPITALIZADORA COLMENA S.A",
    asistencia: "6014010447",
  },
  { nombre: "HDI SEGUROS DE VIDA S.A", asistencia: "204" },
  { nombre: "HDI SEGUROS S.A", asistencia: "204" },
  { nombre: "JMALUCELLI TRAVELERS SEGUROS S.A", asistencia: "6015522350" },
  { nombre: "LA EQUIDAD SEGUROS GENERALES", asistencia: "324" },
  { nombre: "LA PREVISORA S.A", asistencia: "345" },
  { nombre: "LIBERTY SEGUROS S.A", asistencia: "224" },
  { nombre: "MAPFRE COLOMBIA VIDA SEGUROS S.A", asistencia: "624" },
  { nombre: "MAPFRE SEGUROS GENERALES DE COLOMBIA S.A", asistencia: "624" },
  { nombre: "METLIFE COLOMBIA SEGUROS DE VIDA S.A", asistencia: "6013581258" },
  { nombre: "NACIONAL DE SEGUROS S.A", asistencia: "6017463219" },
  { nombre: "OLD MUTUAL SKANDIA", asistencia: "6016584000" },
  { nombre: "PAN AMERICAN LIFE DE COLOMBIA S.A", asistencia: "6017562323" },
  { nombre: "POSITIVA COMPAÑÍA DE SEGUROS S.A", asistencia: "6013307000" },
  { nombre: "QBE SEGUROS S.A", asistencia: "6013190730" },
  { nombre: "SBS SEGUROS COLOMBIA S.A", asistencia: "360" },
  { nombre: "SEGUREXPO DE COLOMBIA S.A", asistencia: "6013266969" },
  { nombre: "SEGUROS ALFA S.A", asistencia: "253" },
  { nombre: "SEGUROS BOLIVAR S.A", asistencia: "322" },
  { nombre: "SEGUROS DE VIDA DEL ESTADO", asistencia: "388" },
  { nombre: "SEGUROS DEL ESTADO S.A", asistencia: "388" },
  { nombre: "SEGUROS GENERALES SURAMERICANA S.A", asistencia: "888" },
  {
    nombre: "SOLUNION COLOMBIA SEGUROS DE CREDITO S.A",
    asistencia: "6015189469",
  },
  { nombre: "ZURICH COLOMBIA SEGUROS S.A", asistencia: "601518848" },
];
